# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2f3c0ca2524f70c85447901b0cd636a95c794440d1a888a521fbb8bca8b7bb55592fb014277ca084c1dcca10091fb7c4dbb57dd2cf270d3d67931984dd9b7c3

test:
  secret_key_base: b8512d26f96c28b48234c91742443275afa33c3fc9e279e403b5fc57dc4da928e65d7fd08e90d3092c8aff32fbbf97862ac7bdf710c13d8d130bb864df4f1580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
